### ISSUE TITLE
Please publish latest version 0.11.2 to Chef Supermarket

### ISSUE THREAD

**Issue by DeploymentKing** [andy-dufour/chef-jboss7#7]
I am new to chef etc so apologies is this is not the correct etiquette.
I have a Berksfile that uses Chef Supermarket which currently uses 0.11.1. When I clicked the link to view source it takes me to 0.11.2 which caused a few headscratching moments until I realised the code I was looking at was not the code that was being run on my instance (more specifically I was falling foul of the hardcoded user and group of "web" that was fixed in cc87c21693a11f15846f3862ef58c9618c272e88

**Comment by andy-dufour** [comment]
Thanks I will be publishing soon, I'm trying to get things setup a continuous delivery pipeline so PR's are automatically tested and merged. Should be done in the coming days.

**Comment by andy-dufour** [comment]
so apparently 'soon' means 6+ months. Sorry for the delay. V1.0.0 is now published to supermarket.
